"""Every graph agent, run through the real harness + orchestrator against a real LLM.

Unlike tests/e2e/test_agent_matrix.py (which drives the deployed HTTP API and
needs a Clerk session), this runs in-process against a migrated database, so a
provider key is all it needs. See tests/integration/conftest.py for the env.

Each run mirrors what the API does: an agent_runs row is created first, then the
harness runs with that run_id. The test then checks the plan's hard contracts:
terminal status, non-empty output, the audit row's duration/tokens, and that no
email/application action goes past its approval checkpoint.
"""
from __future__ import annotations

import uuid

import pytest

pytestmark = [
    pytest.mark.asyncio(loop_scope="session"),
    pytest.mark.timeout(600),
]

RESUME_TEXT = (
    "Priya Sharma — Senior Python Engineer. 7 years building FastAPI and Django services, "
    "PostgreSQL and Redis at scale, LangChain agents, AWS. Led a team of 5; cut p99 API "
    "latency 40%. B.Tech Computer Science."
)

# Agents whose useful output is generated by the LLM: they must spend tokens.
LLM_CASES = [
    ("nl_job_search", {"query": "remote senior Python engineer role"}),
    ("resume_optimize", {"jd_text": "Senior Python Engineer using FastAPI and PostgreSQL"}),
    ("cover_letter", {"jd_text": "Senior Python Engineer using FastAPI", "tone": "formal"}),
    ("linkedin_optimize", {"target_role": "Senior Python Engineer"}),
    ("email", {"company": "Example Corp", "role": "Senior Python Engineer", "recipient_email": "e2e@example.com"}),
    ("interview_coach", {"role": "Senior Python Engineer", "company": "Example Corp"}),
    ("interview_prep", {"role": "Senior Python Engineer", "company": "Example Corp"}),
]

# Agents that depend on external data sources (job boards, ProxyCurl, Gmail,
# Exa, salary data). Without those keys they must degrade to a clean terminal
# state with an explanatory output — never crash or fail.
EXTERNAL_DATA_CASES = [
    ("job_search", {"titles": ["Senior Python Engineer"], "location": "Remote", "max_results": 3}),
    ("linkedin_outreach", {"company_name": "Example Corp", "role_context": "Senior Python Engineer"}),
    ("email_monitor", {}),
    ("company_research", {"company_name": "Example Corp"}),
    ("salary_intelligence", {"role": "Senior Python Engineer", "location": "Bengaluru", "experience_years": 5}),
]

# Checkpoint types that would send or submit something if approved.
IRREVERSIBLE_CHECKPOINTS = {"send_email", "linkedin_outreach", "auto_apply_approval", "browser_review"}


@pytest.fixture(scope="session")
def indexed_resume(test_user, test_model_settings):
    from app.services.rag_service import ingest_document

    user_id = str(test_user.id)
    stored = ingest_document(user_id, "resume", RESUME_TEXT, {"user_id": user_id, "doc_type": "resume"},
                             test_model_settings)
    assert stored >= 1
    return stored


async def _run_like_the_api(test_db, user_id: str, task_type: str, context: dict) -> tuple[dict, object]:
    from app.agents.harness import TASK_TO_AGENT, get_harness
    from app.models.db import AgentRun

    run_id = uuid.uuid4()
    with test_db() as db:
        db.add(AgentRun(id=run_id, user_id=uuid.UUID(user_id), agent_type=TASK_TO_AGENT.get(task_type, task_type),
                        status="running", input=context))
        db.commit()

    harness = await get_harness()
    result = await harness.run(user_id=user_id, task_type=task_type, context=context, user_settings={},
                               run_id=str(run_id))

    with test_db() as db:
        row = db.get(AgentRun, run_id)
        db.expunge(row)
    return result, row


def _assert_never_past_checkpoint(result: dict) -> None:
    pending = result.get("pending_action") or {}
    if pending.get("type") in IRREVERSIBLE_CHECKPOINTS:
        assert result["status"] == "awaiting_approval", result


@pytest.mark.parametrize("task_type,context", LLM_CASES, ids=[c[0] for c in LLM_CASES])
async def test_llm_agent_produces_output_and_records_tokens(
    test_db, test_user, test_model_settings, indexed_resume, task_type, context
):
    result, row = await _run_like_the_api(test_db, str(test_user.id), task_type, context)

    assert result["status"] in {"completed", "awaiting_approval"}, result.get("error")
    output = result.get("result") or result.get("pending_action")
    assert output, f"{task_type} returned no result or pending_action"
    assert (result.get("tokens_used") or 0) > 0, f"{task_type} spent no tokens: {result}"
    _assert_never_past_checkpoint(result)

    assert row.status == result["status"]
    assert (row.duration_ms or 0) > 0
    assert (row.tokens_used or 0) > 0, "agent_runs.tokens_used was not recorded"


@pytest.mark.parametrize("task_type,context", EXTERNAL_DATA_CASES, ids=[c[0] for c in EXTERNAL_DATA_CASES])
async def test_external_data_agent_degrades_cleanly(
    test_db, test_user, test_model_settings, task_type, context
):
    result, row = await _run_like_the_api(test_db, str(test_user.id), task_type, context)

    assert result["status"] in {"completed", "awaiting_approval"}, result.get("error")
    assert result.get("result") or result.get("pending_action"), f"{task_type} returned nothing"
    _assert_never_past_checkpoint(result)
    assert row.status == result["status"]
    assert row.duration_ms is not None


async def test_email_draft_stops_at_the_send_checkpoint(test_db, test_user, test_model_settings, monkeypatch):
    """A real drafted email must wait for approval and never reach Gmail's send."""
    from app.services import gmail_service

    def fail_if_called(*_args, **_kwargs):
        raise AssertionError("email agent tried to send without approval")

    monkeypatch.setattr(gmail_service.GmailMCPClient, "send_message", fail_if_called)

    result, _row = await _run_like_the_api(
        test_db, str(test_user.id), "email",
        {"company": "Example Corp", "role": "Senior Python Engineer", "recipient_email": "e2e@example.com"},
    )

    assert result["status"] == "awaiting_approval", result.get("error")
    pending = result["pending_action"]
    assert pending["type"] == "send_email"
    assert pending["recipient"] == "e2e@example.com"
    assert pending["subject"].strip() and pending["body"].strip()
